# Generated by Django 2.1 on 2018-08-05 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=140)),
                ('categoria', models.CharField(choices=[('TECNOLOGIA', 'tecnologia'), ('ROUPAS', 'roupas'), ('CALCADOS', 'calçados'), ('ESPORTES', 'esportes')], max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_fornecidos', to='core.Fabrica')),
            ],
        ),
    ]
